modified:   GameExec 	new file:   GameExec-Screenshot.jpg 	modified:   README.md

diff --git a/GameExec b/GameExec
--- a/GameExec
+++ b/GameExec
@@ -4,8 +4,8 @@
 #  Remember to edit the script's path in GameExec.desktop if you plan to move it to a different directory from GameExec.
 # Known issues: Sometimes script crashes while trying to launch the game through GameExec.desktop. Prefer running directly from GameExec.
 
-version="1.3"
-changes="\nChangelog: \nAdded ability to include game supported launch parameters (separate each by spaces)."
+version="1.4"
+changes="\nChangelog: \nAdded Start CoreCtrl ability as it improves greatly the performance."
 echo "$(echo $'\n\r')#### Linux Game Launcher v${version} ####"
 echo "by Perseus"
 
@@ -89,7 +89,7 @@ gamenames=()
 while IFS= read -r i; do
  gamenames+=( "$(echo $i | cut -d '=' -f 1)" )
 done < "$gamelist"
- selectedgame=$(zenity --list --title="Games" --text="Select a game to $action:" --column="Game" "${gamenames[@]}" --height=300 --width=500)
+ selectedgame=$(zenity --list --title="Games" --text="Select a game to $action:" --column="Game" "${gamenames[@]}" --height=330 --width=500)
  [[ "$?" -ne 0 || -z "$selectedgame" ]] && desktopmenu
  selectedgamepath=$(grep -Pw "$selectedgame" "$gamelist" | cut -d '=' -f 2)
  gameparams=$(grep -Pw "$selectedgame" "$gamelist" | cut -d '=' -f 3)
@@ -112,12 +112,22 @@ function runwinetricks {
  desktopmenu
 }
 
+# Start CoreCtrl
+function startcorectrl {
+ [ -z $(whereis corectrl | awk '{print $2}') ] && param="--error" && msg="corectrl not found installed. Install CoreCtrl and retry.\nhttps://gitlab.com/corectrl/corectrl" && output && desktopmenu
+ (
+  $(which corectrl)
+  [ "$?" -ne 0 ] && param="--error" && msg="Something went wrong and CoreCtrl returned an unknown error.\nMake sure to have installed a polkit because CoreCtrl requires password.\nhttps://gitlab.com/corectrl/corectrl/-/wikis/Setup" && output
+ )&
+ desktopmenu
+}
+
 # Enable or disable gamemode
 function enablegamemode {
  [ -z $(whereis gamemoderun | awk '{print $2}') ] && param="--error" && msg="gamemoderun not found installed. Install GameMode and retry." && output && desktopmenu
  [ -z "$gamemode" ] && gamemode=1 || gamemode=
  [ -z "$gamemode" ] && gamemodestate="disabled" || gamemodestate="enabled"
- param="--info" && msg="GameMode optimisations are now $gamemodestate." && output && desktopmenu
+ param="--info" && msg="GameMode optimisations are now $gamemodestate.\nAttention: Sometimes GameMode decreases performance. Test with and without it depending the game." && output && desktopmenu
 }
 
 # Enable or disable OSD function
@@ -125,7 +135,7 @@ function osd {
  selectedosditem=$(zenity --list --radiolist --text="Linux Game Launcher v${version} - OSD menu" \
  --column="Select" --column="Operation" FALSE "Basic info (Just FPS and GPU usage info)" \
  TRUE "Normal info (More detailed info of GPU, Drivers etc)" FALSE "Full info (All available items displayed)" \
- FALSE "Disable DXVK OSD HUD" --height=300 --width=500)
+ FALSE "Disable DXVK OSD HUD" --height=330 --width=500)
  [ "$?" -ne 0 ] && desktopmenu
 
 grep -q ^Basic <<<"$selectedosditem" && export DXVK_HUD=fps,gpuload && desktopmenu
@@ -158,12 +168,13 @@ function update {
 function desktopmenu {
 selectedmenuitem=$(zenity --list --radiolist --text="Linux Game Launcher v${version} - Main menu" \
  --column="Select" --column="Operation" TRUE "Launch a game" FALSE "Add a new game" \
- FALSE "Remove a game from the game list" FLASE "GameMode optimisations (requires gamemode)" FALSE "DXVK OSD HUD (On Screen Display)" FALSE "Winetricks (requires wine and winetricks)" \
- FALSE "Reset $(basename $0)" FALSE "Update $(basename $0)" --height=300 --width=500)
+ FALSE "Remove a game from the game list" FALSE "CoreCtrl (requires corectrl)" FALSE "GameMode optimisations (requires gamemode)" FALSE "DXVK OSD HUD (On Screen Display)" FALSE "Winetricks (requires wine and winetricks)" \
+ FALSE "Reset $(basename $0)" FALSE "Update $(basename $0)" --height=330 --width=500)
 
 grep -q ^Launch <<<"$selectedmenuitem" && launchgame
 grep -q ^Add <<<"$selectedmenuitem" && addgame
 grep -q ^Remove <<<"$selectedmenuitem" && removegame
+grep -q ^CoreCtrl <<<"$selectedmenuitem" && startcorectrl
 grep -q ^GameMode <<<"$selectedmenuitem" && enablegamemode
 grep -q ^DXVK <<<"$selectedmenuitem" && osd
 grep -q ^Winetricks <<<"$selectedmenuitem" && runwinetricks
