modified:   GameExec

diff --git a/GameExec b/GameExec
--- a/GameExec
+++ b/GameExec
@@ -221,7 +221,7 @@ protononline="$protondir"
 # Drop error if Proton not installed and offer auto install or update
 if [ ! -f "$protonexec" ] || [ ! -z "$updateproton" ]; then
  [ ! -f "$protonexec" ] && param="--question" && msg="Proton GE Custom not found installed or not configured. \nWould you like to verify or install it now?" && output
-  [ "$?" -ne 0 ] && param="--error" && msg="Cannot start without Proton GE Custom installed. Exiting." && output && exit 1
+  [ "$?" = -1 ] && param="--error" && msg="Cannot start without Proton GE Custom installed. Exiting." && output && exit 1
  (
   echo "1" ; sleep 1
   echo "# Installing $protononline..." ; sleep 1
