modified:   GameExec 	new file:   GameExec-Screenshot.jpg 	modified:   README.md

diff --git a/GameExec b/GameExec
--- a/GameExec
+++ b/GameExec
@@ -13,6 +13,7 @@ gamelist="$scriptpath/GameList.txt"
 if [ -f "$config" ]; then
 protonbottle=$(grep "ProtonBottle" "$config" | cut -d "=" -f 2)
 protonexec=$(grep "ProtonExec" "$config" | cut -d "=" -f 2)
+[ ! -z "$protonexec" ] && protoninstalled=$(dirname "$protonexec" | xargs basename)
 fi
 
 # Output in zenity
@@ -58,6 +59,13 @@ function removegame {
  sed -i "/$selectedgame/d" "$gamelist" && param="--info" && msg="Removed: $selectedgame" && output && desktopmenu
 }
 
+function runwinetricks {
+  [ -z $(whereis winetricks | awk '{print $2}') ] && param="--error" && msg="winetricks not found installed. Install winetricks and retry." && output && desktopmenu
+  [ -z $(whereis wine | awk '{print $2}') ] && param="--error" && msg="wine not found installed. Install wine and retry." && output && desktopmenu
+ WINEPREFIX="${protonbottle}/pfx" winetricks
+ desktopmenu
+}
+
 # reset to default function
 function reset {
  param="--question" && msg="This option will reset GameExec to default.\nIt will remove your Proton bottle: $protonbottle.\nand your config file: ${config}.\nYour game list will remain in tact.\nDo you want to proceed?" && output
@@ -81,14 +89,16 @@ function launchgame {
   #msg="Game execution failed." && output && exit 1
 }
 
+# main menu function
 function desktopmenu {
 selectedmenuitem=$(zenity --list --radiolist --text="Linux Game Launcher - Main menu" \
  --column="Select" --column="Operation" TRUE "Launch a game" FALSE "Add a new game" \
- FALSE "Remove a game from the game list" FALSE "Reset GameExec" --height=300 --width=500)
+ FALSE "Remove a game from the game list" FALSE "Winetricks (Requires wine and winetricks)" FALSE "Reset GameExec" --height=300 --width=500)
 
 grep -q ^Launch <<<"$selectedmenuitem" && launchgame
 grep -q ^Add <<<"$selectedmenuitem" && addgame
 grep -q ^Remove <<<"$selectedmenuitem" && removegame
+grep -q ^Winetricks <<<"$selectedmenuitem" && runwinetricks
 grep -q ^Reset <<<"$selectedmenuitem" && reset
 echo "$(echo $'\n\r')#### Linux Game Launcher Finished. ####"
 exit 0
@@ -117,27 +127,36 @@ else
  #chk || (param="--error" && msg="Steam still not running. Exiting." && output && exit 1)
 fi
 
-# Drop error if Proton not installed and offer to auto install
-[ ! -f "$protonexec" ] && param="--question" && msg="Proton not found installed or not configured. \nWould you like to verify or install it now?" && output
-[ "$?" -ne 0 ] && [ ! -f "$protonexec" ] && param="--error" && msg="Cannot start without Proton installed. Exiting." && output && exit 1
+# Check if Proton is installed and also check for update
 compatpath="${HOME}/.steam/root/compatibilitytools.d"
 protonurl="https://github.com$(curl -s -L https://github.com/GloriousEggroll/proton-ge-custom/releases/latest | grep 'tar.gz' | head -1 | cut -d '"' -f 2)"
 protonfile=$(basename "$protonurl")
 protondir="${protonfile/.tar.gz/}"
 protonfullpath="${compatpath}/${protondir}"
-protonexec="${protonfullpath}/proton"
-if [ -f "$protonexec" ]; then
- [ ! -f "$config" ] && param="--info" && msg="$protondir found installed and will be added to the config." && output || echo
-else
+protononline="$protondir"
+[ ! -z "$protoninstalled" ] && [ ! -z "$protononline" ] && [ "$protoninstalled" != "$protononline" ] && \
+ param="--question" && msg="An updated version of Proton is available online: ${protononline}. \nWould you like to update it now?" && output && \
+  [ "$?" -eq 0 ] && updateproton=1
+
+# Drop error if Proton not installed and offer auto install or update
+if [ ! -f "$protonexec" ] || [ ! -z "$updateproton" ]; then
+ [ ! -f "$protonexec" ] && param="--question" && msg="Proton not found installed or not configured. \nWould you like to verify or install it now?" && output && \
+  [ "$?" -ne 0 ] && param="--error" && msg="Cannot start without Proton installed. Exiting." && output && exit 1
 # ADD ZENITY PROGRESS HERE
+ echo "Installing $protononline..."
+ [ ! -z "$updateproton" ] && printf "Cleaning previously installed Proton..." && rm -rf "${compatpath}/${protoninstalled}" && echo "Done."
  mkdir -p "$compatpath" && \
   curl -L "${protonurl}" -o "${compatpath}/Proton.tar.gz" && \
   printf "Uncompressing..." && \
+  rm -rf "$protonfullpath" 2>/dev/null && \
   tar xfz "${compatpath}/Proton.tar.gz" --directory "${compatpath}/" && \
   rm "${compatpath}/Proton.tar.gz" && \
   echo "Done." && \
   [ -f "$protonexec" ] && \
+  protonexec="${protonfullpath}/proton" && \
   param="--info" && msg="$protondir is now installed." && output
+else
+ [ ! -f "$config" ] && param="--info" && msg="$protondir found installed and will be added to the config." && output || echo
 fi
 
 # Creating config file if not found
