modified:   GameExec

diff --git a/GameExec b/GameExec
--- a/GameExec
+++ b/GameExec
@@ -164,16 +164,16 @@ protondir="${protonfile/.tar.gz/}"
 protonfullpath="${compatpath}/${protondir}"
 protononline="$protondir"
 [ ! -z "$protoninstalled" ] && [ ! -z "$protononline" ] && [ "$protoninstalled" != "$protononline" ] && \
- param="--question" && msg="An updated version of Proton is available online: ${protononline}. \nWould you like to update it now?" && output && \
+ param="--question" && msg="An updated version of Proton GE Custom is available online: ${protononline}. \nWould you like to update it now?" && output && \
   [ "$?" -eq 0 ] && updateproton=1
 
 # Drop error if Proton not installed and offer auto install or update
 if [ ! -f "$protonexec" ] || [ ! -z "$updateproton" ]; then
- [ ! -f "$protonexec" ] && param="--question" && msg="Proton not found installed or not configured. \nWould you like to verify or install it now?" && output
-  [ "$?" -ne 0 ] && param="--error" && msg="Cannot start without Proton installed. Exiting." && output && exit 1
+ [ ! -f "$protonexec" ] && param="--question" && msg="Proton GE Custom not found installed or not configured. \nWould you like to verify or install it now?" && output
+  [ "$?" -ne 0 ] && param="--error" && msg="Cannot start without Proton GE Custom installed. Exiting." && output && exit 1
 # ADD ZENITY PROGRESS HERE
  echo "Installing $protononline..."
- [ ! -z "$updateproton" ] && printf "Cleaning previously installed Proton..." && rm -rf "${compatpath}/${protoninstalled}" && echo "Done."
+ [ ! -z "$updateproton" ] && printf "Cleaning previously installed Proton GE Custom..." && rm -rf "${compatpath}/${protoninstalled}" && echo "Done."
  mkdir -p "$compatpath" && \
   curl -L "${protonurl}" -o "${compatpath}/Proton.tar.gz" && \
   printf "Uncompressing..." && \
